### ISSUE TITLE
Unable to Reproduce: Training error

### ISSUE THREAD

**Issue by sramakrishnan247** [SurajDonthi/Multi-Camera-Person-Re-Identification#13]
Hey,

I created a conda environment with python=3.6 and installed the packages in requirements.txt.
When I run the training command, I get the following:

```
$ python mtmct_reid/main.py --data_dir data/raw/Market-1501-v15.09.15 --save_distribution data/raw/Market-1501-v15.09.15/st_distribution.pkl --gpus 1 --max_epochs 1

Arguments: 
Namespace(accumulate_grad_batches=1, amp_backend='native', amp_level='O2', auto_lr_find=False, auto_scale_batch_size=False, auto_select_gpus=False, benchmark=False, check_val_every_n_epoch=1, checkpoint_callback=True, color_jitter=False, criterion='cross_entropy', data_dir='data/raw/Market-1501-v15.09.15', debug=None, default_root_dir=None, description=None, deterministic=False, distributed_backend=None, early_stop_callback=False, fast_dev_run=False, git_tag=None, gpus=1, gradient_clip_val=0, learning_rate=0.1, limit_test_batches=1.0, limit_train_batches=1.0, limit_val_batches=1.0, log_gpu_memory=None, log_path='./logs', log_save_interval=100, logger=True, max_epochs=1, max_steps=None, min_epochs=1, min_steps=None, num_nodes=1, num_processes=1, num_sanity_val_steps=2, num_workers=4, overfit_batches=0.0, overfit_pct=None, precision=32, prepare_data_per_node=True, process_position=0, profiler=None, progress_bar_refresh_rate=1, query_subdir='query', random_erasing=0.0, reload_dataloaders_every_epoch=False, replace_sampler_ddp=True, rerank=False, resume_from_checkpoint=None, row_log_interval=50, save_distribution='data/raw/Market-1501-v15.09.15/st_distribution.pkl', save_features=False, st_distribution=None, sync_batchnorm=False, terminate_on_nan=False, test_batchsize=16, test_percent_check=None, test_subdir='bounding_box_test', tpu_cores=<function Trainer._gpus_arg_default at 0x7fc86038ea60>, track_grad_norm=-1, train_batchsize=16, train_percent_check=None, train_subdir='bounding_box_train', truncated_bptt_steps=None, val_batchsize=16, val_check_interval=1.0, val_percent_check=None, weights_save_path=None, weights_summary='top')

/home/mli/sramakrishnan/miniconda3/envs/streid/lib/python3.6/site-packages/torchvision/transforms/transforms.py:258: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  "Argument interpolation should be of type InterpolationMode instead of int. "


Generating Spatial-Temporal Distribution.



Saving distribution at data/raw/Market-1501-v15.09.15/st_distribution.pkl
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
CUDA_VISIBLE_DEVICES: [0]
/home/mli/sramakrishnan/miniconda3/envs/streid/lib/python3.6/site-packages/pytorch_lightning/utilities/distributed.py:37: UserWarning: Could not log computational graph since the `model.example_input_array` attribute is not set or `input_array` was not given
  warnings.warn(*args, **kwargs)

  | Name        | Type            | Params
------------------------------------------------
0 | model       | Sequential      | 23 M  
1 | dropout     | Dropout         | 0     
2 | classifier0 | ClassifierBlock | 718 K 
3 | classifier1 | ClassifierBlock | 718 K 
4 | classifier2 | ClassifierBlock | 718 K 
5 | classifier3 | ClassifierBlock | 718 K 
6 | classifier4 | ClassifierBlock | 718 K 
7 | classifier5 | ClassifierBlock | 718 K 
/home/mli/sramakrishnan/miniconda3/envs/streid/lib/python3.6/site-packages/pytorch_lightning/utilities/distributed.py:37: UserWarning: Your val_dataloader has `shuffle=True`, it is best practice to turn this off for validation and test dataloaders.
  warnings.warn(*args, **kwargs)
Validation sanity check: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "mtmct_reid/main.py", line 57, in <module>
    main(args)
  File "mtmct_reid/main.py", line 43, in main
    trainer.fit(model, data_module)
  File "/home/mli/sramakrishnan/miniconda3/envs/streid/lib/python3.6/site-packages/pytorch_lightning/trainer/states.py", line 48, in wrapped_fn
    result = fn(self, *args, **kwargs)
  File "/home/mli/sramakrishnan/miniconda3/envs/streid/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1073, in fit
    results = self.accelerator_backend.train(model)
  File "/home/mli/sramakrishnan/miniconda3/envs/streid/lib/python3.6/site-packages/pytorch_lightning/accelerators/gpu_backend.py", line 51, in train
    results = self.trainer.run_pretrain_routine(model)
  File "/home/mli/sramakrishnan/miniconda3/envs/streid/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1224, in run_pretrain_routine
    self._run_sanity_check(ref_model, model)
  File "/home/mli/sramakrishnan/miniconda3/envs/streid/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1257, in _run_sanity_check
    eval_results = self._evaluate(model, self.val_dataloaders, max_batches, False)
  File "/home/mli/sramakrishnan/miniconda3/envs/streid/lib/python3.6/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 333, in _evaluate
    output = self.evaluation_forward(model, batch, batch_idx, dataloader_idx, test_mode)
  File "/home/mli/sramakrishnan/miniconda3/envs/streid/lib/python3.6/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 687, in evaluation_forward
    output = model.validation_step(*args)
  File "/mnt/ssd/sramakrishnan/tracking/Multi-Camera-Person-Re-Identification/mtmct_reid/engine.py", line 173, in validation_step
    self.log_dict(self.val_logs, logger=False)
  File "/home/mli/sramakrishnan/miniconda3/envs/streid/lib/python3.6/site-packages/torch/nn/modules/module.py", line 948, in __getattr__
    type(self).__name__, name))
AttributeError: 'ST_ReID' object has no attribute 'log_dict'
```

Please let me know if there is something that I am missing.

**Comment by sramakrishnan247** [comment]
FIX: Update Pytorch lightning version.

Pull request after testing:
https://github.com/SurajDonthi/Multi-Camera-Person-Re-Identification/pull/14
